name: Publish package

on:
  push:
    branches:
      - main

    paths:
      - CHANGELOG.md
  workflow_dispatch:

jobs:
  build_package:
    uses: telicent-oss/telicent-ds/.github/workflows/build-package.yml@main
    secrets: inherit

  publish_package:
    runs-on: ubuntu-latest
    needs: build_package
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: design-system-build-artifacts
      - name: Verify artifacts
        run: ls -la ${{ github.workspace }}
      - run: npm publish --access public --provenance
