name: Publish package

on:
  push:
    branches:
      - main

    paths:
      - CHANGELOG.md
  workflow_dispatch:

jobs:
  publish_package:
    uses: telicent-oss/telicent-ds/.github/workflows/build-package.yml@main
    steps:
      - run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
