name: Publish package

on:
  push:
    branches:
      - main

    paths:
      - CHANGELOG.md
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: telicent-oss/telicent-ds/.github/workflows/build-package.yml@main

      - name: Publish package
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
