name: Publish package

on:
  push:
    branches:
      - main

    paths:
      - CHANGELOG.md
  workflow_dispatch:

jobs:
  build_package:
    uses: telicent-oss/telicent-ds/.github/workflows/build-package.yml@main
    with:
      node-auth-token: ${{ secrets.NPM_REGISTRY_TOKEN }}

  publish_package:
    runs-on: ubuntu-latest
    needs: build_package
    steps:
      - run: npm publish --access public --provenance
