name: Update storybook
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build-storybook
      - run: |
          mkdir -p storybook
          cp -R storybook-static/ storybook/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./storybook
